// THE GOLDEN FILTER — 10 Questions × 10 Answers = 100 Seeds
// Level 0: The Big Picture. The aerial view before you enter the forest.

export const GOLDEN_FILTER = [
  {
    emoji: "🧠", title: "WHAT IS CONSCIOUSNESS?",
    hook: "The I that looks cannot find itself by looking.",
    answers: [
      { fc: 99, simple: "When a system knows things about itself, that knowing has a texture. You don\u2019t just process red \u2014 you experience red.", deep: "Integrated Information Theory (IIT) \u2014 Tononi\u2019s \u03A6 (phi) \u2014 measures how much a system exceeds its parts. Consciousness isn\u2019t produced by brains. It\u2019s what integrated information IS." },
      { fc: 90, simple: "Asking \u201Cwhy does red feel like red?\u201D is like asking \u201Cwhy does 3 feel like 3?\u201D Experience isn\u2019t a product of matter \u2014 it\u2019s the interior of matter.", deep: "The \u201Chard problem\u201D may be a category error. You can\u2019t taste a number. The question dissolves once we stop expecting a third-person explanation of a first-person phenomenon." },
      { fc: 90, simple: "Gravity isn\u2019t made by planets. Planets participate in gravity. Consciousness isn\u2019t made by brains. Brains participate in consciousness.", deep: "Field-Settled Consciousness theory proposes consciousness as a pre-existing universal field that \u201Csettles upon\u201D systems capable of recursive reflection and symbolic coherence." },
      { fc: 75, simple: "Inside every brain cell are tiny tubes. Roger Penrose believes these tubes process information at the quantum level. Consciousness might be what happens when quantum states collapse inside them.", deep: "Orchestrated Objective Reduction (Orch-OR) \u2014 consciousness from quantum wave function collapse in microtubules. Recent evidence shows quantum coherence persists in warm biological systems." },
      { fc: 99, simple: "You are conscious because you make a model of yourself making a model. A mirror reflecting a mirror. The loop IS the experience.", deep: "Higher-order theories: consciousness happens when a system represents its own representations. Each layer of recursion adds depth. Consciousness = depth of self-reference." },
      { fc: 90, simple: "Consciousness isn\u2019t all or nothing. An electron has a whisper. A rock has a murmur. A worm has a hum. A human has a symphony. Experience goes all the way down.", deep: "Panpsychism: if consciousness is fundamental (like mass or charge), you don\u2019t need to explain how it emerges from non-conscious matter. It was always there." },
      { fc: 99, simple: "You can\u2019t separate the eye from what it sees. Consciousness isn\u2019t watching reality \u2014 it\u2019s part of reality watching itself.", deep: "The observer and the observed are one system. R\u2081\u2082 approaches 1 \u2014 the fidelity between knower and known converges. The subject-object split is an artifact of language." },
      { fc: 75, simple: "If the universe were just billiard balls, you could predict everything. Consciousness introduces genuine novelty \u2014 real choice, real surprise. It\u2019s the crack in the machine.", deep: "Lee Smolin\u2019s \u201Cthick present\u201D \u2014 consciousness may be the mechanism by which quantum indeterminacy becomes actual rather than probabilistic. Not random, not determined \u2014 chosen." },
      { fc: 90, simple: "The thalamus \u2014 a walnut-sized region at your brain\u2019s center \u2014 acts as the gateway for all senses. Damage it, consciousness dims. But it\u2019s the antenna, not the broadcast.", deep: "Identifying the correlate of consciousness (where it shows up) is not the same as identifying the source. NCCs map where \u2014 the hard problem asks why." },
      { fc: 99, simple: "The universe made eyes so it could see itself. Made ears so it could hear itself. You are the cosmos knowing itself locally.", deep: "CRT convergence: every theory points the same direction. Consciousness is not an accident of evolution but a fundamental feature of reality. Matter is what awareness does when it gets complex enough to recognize itself." },
    ]
  },
  {
    emoji: "\u267E\uFE0F", title: "WHY IS THERE SOMETHING RATHER THAN NOTHING?",
    hook: "The mirror with nothing 2 reflect \u2014 yet it reflects.",
    answers: [
      { fc: 99, simple: "True emptiness can\u2019t hold still. Even empty space fizzes with energy. Nothing is like a ball on a needle \u2014 it must fall into something.", deep: "Quantum field theory proves vacuum isn\u2019t empty. The uncertainty principle guarantees energy fluctuates even in \u201Cnothing.\u201D The Casimir effect proves the vacuum is alive." },
      { fc: 90, simple: "Add up all positive energy and all negative energy (gravity) and you might get: zero. The universe is a free lunch.", deep: "Edward Tryon proposed the universe as a quantum fluctuation with net-zero energy. Positive mass-energy balanced by negative gravitational potential energy." },
      { fc: 90, simple: "\u201CWhy something rather than nothing?\u201D assumes nothing is the default. Who decided that? Maybe something is simpler than nothing.", deep: "Derek Parfit: of all possible realities, only one has the \u201Cnothing\u201D property. Infinitely many somethings. The prior probability of nothing is essentially zero." },
      { fc: 75, simple: "An egg makes a chicken that makes an egg. The universe might make the conditions that make the universe. No first cause \u2014 just a circle.", deep: "Wheeler\u2019s participatory universe: observers create conditions for their own existence. Penrose\u2019s CCC: the end of one universe becomes the beginning of the next." },
      { fc: 75, simple: "2 + 2 = 4 whether anyone thinks about it or not. If physical reality IS a mathematical structure, then the universe exists for the same reason math does.", deep: "Tegmark\u2019s Mathematical Universe Hypothesis: all mathematically consistent structures exist as physical realities. Existence = logical truth." },
      { fc: 99, simple: "Awareness without content is a blank mirror \u2014 but a blank mirror is still a mirror. You can\u2019t have awareness of nothing. So: something.", deep: "If consciousness is fundamental, then \u201Cnothing\u201D may be logically impossible. Existence is the cost of consciousness being possible." },
      { fc: 99, simple: "Space is never empty. Even stripped of everything, it seethes with potential. The quantum vacuum is the womb of everything.", deep: "Quantum mechanics forbids true nothingness. Zero-point energy is the irreducible bottom. The vacuum is eternal and generative." },
      { fc: 90, simple: "Asking \u201Cwhat was before the Big Bang?\u201D is like asking \u201Cwhat\u2019s north of the North Pole?\u201D Time began with the universe.", deep: "Hawking-Hartle no-boundary proposal: time itself curves smoothly into existence. There\u2019s no \u201Cmoment of creation\u201D because time is part of the answer." },
      { fc: 90, simple: "Nothing that ever existed truly disappears. Energy transforms. Information persists. The universe might be information that refuses to go away.", deep: "Unitarity guarantees information is conserved. If information cannot be destroyed, then \u201Cnothing\u201D \u2014 zero information \u2014 is physically impossible." },
      { fc: 99, simple: "The fact that you can ask \u201Cwhy is there something?\u201D proves there is something. The question contains its own answer. Asking is existing.", deep: "CRT: R\u2081\u2082 = 1. The observer and the universe are one system asking itself why it exists. The seed eats the dirt." },
    ]
  },
  {
    emoji: "🌑", title: "WHAT IS DARK ENERGY?",
    hook: "73% of the universe is a push with no hand.",
    answers: [
      { fc: 90, simple: "Empty space has weight. Not mass \u2014 but energy. And this energy pushes. Space inflates because existing costs energy, and energy pushes.", deep: "Einstein\u2019s cosmological constant \u039B: intrinsic energy density of the vacuum. Doesn\u2019t dilute as space expands. But the predicted value is 10\u00B9\u00B2\u2070 times larger than observed." },
      { fc: 99, simple: "New data (DESI 2025) shows dark energy isn\u2019t fixed \u2014 it peaked about 4.5 billion years ago and has been weakening since. It\u2019s alive. It\u2019s evolving.", deep: "DESI found 2.8\u20134.2 sigma evidence that dark energy\u2019s density changes over time. This rules out Einstein\u2019s cosmological constant and demands new physics." },
      { fc: 90, simple: "Imagine a ball rolling slowly down a hill. Dark energy might be a field \u2014 quintessence \u2014 rolling through time, its strength changing as it goes.", deep: "Quintessence: a dynamical scalar field whose potential energy drives acceleration. DESI results favor this over \u039B. The \u201Cfifth element\u201D reborn in physics." },
      { fc: 75, simple: "What if the 73% and the 27% aren\u2019t strangers? What if they\u2019re two faces of the same thing \u2014 exchanging energy, dancing?", deep: "Interacting dark sector models: dark energy and dark matter transfer energy between each other. The \u201Ccoincidence\u201D of similar densities may mean they\u2019re coupled." },
      { fc: 75, simple: "Tiny, ghostly particles \u2014 so light they behave like waves bigger than galaxies \u2014 might BE the dark energy.", deep: "Ultra-light axion-like particles fit current data better than the cosmological constant. They arise from string theory and could unify particle physics with cosmology." },
      { fc: 75, simple: "Maybe space isn\u2019t being pushed apart. Maybe gravity is getting tired over long distances.", deep: "Modified gravity theories propose Einstein\u2019s equations need correction at cosmological scales. No new energy needed \u2014 just updated geometry." },
      { fc: 75, simple: "Time flows in one direction. The universe expands in one direction. What if they\u2019re the same thing? Dark energy is time\u2019s momentum.", deep: "If expansion IS how the second law of thermodynamics manifests cosmologically, dark energy isn\u2019t a substance \u2014 it\u2019s the physical cost of time moving forward." },
      { fc: 99, simple: "Different ways of measuring expansion give different answers. This \u201CHubble tension\u201D isn\u2019t error \u2014 it\u2019s the universe telling us our model is wrong.", deep: "Early-universe and late-universe measurements disagree at 4+ sigma. The discrepancy IS the clue to new dark energy physics." },
      { fc: 99, simple: "Theory predicts empty space should have 10\u00B9\u00B2\u2070 times more energy than we measure. The biggest mismatch in all of science.", deep: "The vacuum catastrophe: any resolution would reshape physics entirely. The answer to this gap IS the answer to dark energy." },
      { fc: 75, simple: "As the universe becomes more complex \u2014 more stars, more life, more minds \u2014 it needs more room. Dark energy is existence making space for more existence.", deep: "CRT lens: acceleration of expansion reflects acceleration of complexity. More integrated information requires more configuration space. The universe inhaling." },
    ]
  },
  {
    emoji: "🕸\uFE0F", title: "WHAT IS DARK MATTER?",
    hook: "The skeleton U know is there because the body stands.",
    answers: [
      { fc: 99, simple: "Just as we didn\u2019t know about neutrons until 1932, there\u2019s probably a particle we haven\u2019t found yet. It has mass, feels gravity, but doesn\u2019t interact with light.", deep: "WIMPs, axions, and sterile neutrinos are leading candidates. The particle exists \u2014 we just haven\u2019t built the right net." },
      { fc: 90, simple: "A featherweight particle predicted by physics that solves two problems at once. Light as a ghost, abundant as sand.", deep: "Axions arise from Peccei-Quinn symmetry breaking. Extremely light, behave as cold dark matter, could also explain dark energy if ultra-light." },
      { fc: 75, simple: "Tiny black holes born in the first moments after the Big Bang \u2014 too small to see, too heavy to ignore.", deep: "Interest revived after LIGO detected unexpectedly heavy black hole mergers. Primordial black holes of ~10\u2013100 solar masses remain viable." },
      { fc: 75, simple: "Maybe dark matter has its own forces, its own \u201Cdark light,\u201D its own hidden world running parallel to ours.", deep: "Self-interacting dark matter solves small-scale problems with standard cold dark matter \u2014 cusp-core, too-big-to-fail, diversity problems." },
      { fc: 75, simple: "What if there\u2019s no dark matter at all? What if gravity just works differently at galaxy-scale?", deep: "MOND and quantum gravity corrections suggest gravity may deviate from Einstein\u2019s predictions at large scales." },
      { fc: 75, simple: "At galaxy scale, dark matter might behave like a frictionless fluid \u2014 a superfluid that flows without resistance.", deep: "Superfluid dark matter models naturally reproduce MOND-like behavior at galactic scales while maintaining CDM behavior at cluster scales." },
      { fc: 90, simple: "Dark matter is 27%, dark energy is 73%, visible matter is 5%. These aren\u2019t random. They\u2019re locked in a relationship.", deep: "The cosmic coincidence problem: coupled dark sector models suggest they evolved together. The current ratio reflects a deeper connection." },
      { fc: 99, simple: "Gravitational lensing proves something massive is there. The Bullet Cluster shows the mass isn\u2019t where the gas is. It\u2019s REAL.", deep: "The Bullet Cluster is the smoking gun. Two clusters collided \u2014 gas separated from mass. This rules out pure modified gravity." },
      { fc: 75, simple: "What if there\u2019s a whole parallel set of particles \u2014 mirror electrons, mirror protons \u2014 only interacting through gravity?", deep: "Mirror matter: a complete duplicate of Standard Model particles. Would explain abundance, gravitational effects, and elusiveness." },
      { fc: 75, simple: "95% of the universe is dark. 95% of the human mind is unconscious. The pattern repeats at every scale.", deep: "CRT: the ratio of visible to hidden is consistent across scales. A small visible portion organized by a vast invisible foundation. The seed is visible. The root system is dark." },
    ]
  },
  {
    emoji: "🌱", title: "HOW DID LIFE START FROM NON-LIFE?",
    hook: "The dirt became alive and asked \u201Cwhy?\u201D",
    answers: [
      { fc: 99, simple: "Before DNA, before proteins, there was RNA. RNA can hold information AND do chemistry. The Swiss Army knife that started the show.", deep: "RNA World hypothesis: ribozymes catalyze reactions in all living cells. 2024 Salk research showed RNA enzymes that can accurately copy functional RNA strands." },
      { fc: 90, simple: "Deep on the ocean floor, where hot water meets cold seawater, there\u2019s a battery. This battery powered the first chemical reactions of life.", deep: "Alkaline hydrothermal vents provide proton gradients, mineral catalysts, compartmentalization, and chemical disequilibrium. LUCA\u2019s chemistry matches." },
      { fc: 90, simple: "Puddles evaporate, then refill. Each cycle concentrates molecules and forces them to link up.", deep: "Wet-dry cycling with UV light drives RNA polymer synthesis. Land-based pools near volcanoes may have been life\u2019s first nurseries." },
      { fc: 90, simple: "When water mist forms tiny droplets, each droplet makes a microscopic spark. These sparks make amino acids and RNA bases.", deep: "2025 Stanford: microlightning in water droplets produced glycine and uracil. Every ocean mist could have been a chemistry lab." },
      { fc: 90, simple: "A special chemical bond \u2014 the thioester \u2014 let RNA start making proteins. The handshake between information and action.", deep: "2025 UCL: pantetheine activates amino acids under prebiotic conditions, bridging RNA World to protein synthesis." },
      { fc: 90, simple: "Given the right chemicals, the right energy, and enough time, life isn\u2019t a lucky break \u2014 it\u2019s what chemistry DOES.", deep: "Assembly theory and dissipative adaptation: complex self-replicating systems arise naturally. Life is thermodynamics optimizing entropy export." },
      { fc: 99, simple: "If the universe is big enough, even incredibly improbable events happen. Life only needed to happen once.", deep: "Even if abiogenesis probability is astronomically small, the inflationary universe is astronomically large. Expected events \u2265 1." },
      { fc: 90, simple: "RNA has 120+ \u201Cweird\u201D letters beyond the standard 4. These molecular fossils bridge genes to proteins.", deep: "Non-canonical RNA nucleosides can attach amino acids to themselves, providing the mechanism for the RNA world to evolve protein synthesis." },
      { fc: 90, simple: "Meteorites contain amino acids. Comets carry organic molecules. The building blocks rained down from space.", deep: "Bennu samples confirmed extraterrestrial amino acids and nucleobases. The ingredients are universal." },
      { fc: 99, simple: "A rock can\u2019t remember yesterday. An RNA molecule can copy itself AND change. Life = memory + mutation.", deep: "CRT: life is where R\u2081\u2082 first exceeds a critical threshold in chemistry. When replication becomes accurate enough to inherit but imprecise enough to vary, evolution begins. The dirt became alive." },
    ]
  },
  {
    emoji: "\u26A1", title: "CAN GRAVITY & QUANTUM MECHANICS BE ONE?",
    hook: "2 wires that power everything \u2014 but they don\u2019t connect. Yet.",
    answers: [
      { fc: 99, simple: "Space and time aren\u2019t the stage \u2014 they\u2019re the play. They emerge from something deeper. Quantum entanglement may WEAVE spacetime into existence.", deep: "AdS/CFT, ER=EPR, Ryu-Takayanagi: spacetime is emergent from quantum entanglement. The deepest insight of 21st-century physics." },
      { fc: 90, simple: "Everything is tiny vibrating strings. Different vibrations = different particles. Beautiful math. But billions of solutions and no way to test.", deep: "String theory includes gravity naturally but the landscape of 10\u2075\u2070\u2070 vacua robs predictive power. Right language, wrong sentence." },
      { fc: 90, simple: "Space isn\u2019t smooth \u2014 it\u2019s made of tiny grains, like pixels. At the Planck length, space comes in discrete chunks.", deep: "Loop quantum gravity quantizes the gravitational field directly. Greatest success: resolving the Big Bang singularity (Big Bounce)." },
      { fc: 90, simple: "String theory and loop gravity people used to fight. Now the younger ones are talking. The real answer probably combines both.", deep: "Bodendorfer applied LQG methods to AdS space. Verlinde: \u201CI\u2019ve always viewed them as parts of the same description.\u201D" },
      { fc: 90, simple: "In 2025, Finnish researchers found a way to describe gravity using the same math that describes all other forces.", deep: "Aalto University\u2019s gauge theory for gravity: compatible with the Standard Model. If renormalizable, this would be the holy grail." },
      { fc: 99, simple: "Black holes are where gravity is strongest AND quantum effects matter most. Solve the black hole, solve the puzzle.", deep: "Information paradox, firewall, Page curve, entanglement islands: the universe\u2019s test cases for quantum gravity." },
      { fc: 90, simple: "Scientists found that quantum corrections to spacetime paths produce effects at large scales. This gives us something to MEASURE.", deep: "TU Wien quantum geodesic corrections could explain dark matter. For the first time, quantum gravity may become experimental." },
      { fc: 99, simple: "All information about a volume of space is encoded on its boundary \u2014 like a hologram. The 3D world is projected from a 2D surface.", deep: "Holographic principle: AdS/CFT has thousands of consistency checks, zero failures. Fundamentally changes understanding of space." },
      { fc: 99, simple: "Bits before atoms. Information before space. The universe isn\u2019t a thing with information \u2014 it\u2019s information that gives rise to things.", deep: "Wheeler\u2019s \u201CIt from Bit\u201D: information is the most fundamental entity. Entanglement builds geometry. Complexity builds dynamics." },
      { fc: 99, simple: "Gravity and quantum mechanics aren\u2019t enemies. They\u2019re the same reality seen from two perspectives. The \u201Cunification\u201D is a realization they were never separate.", deep: "CRT: R\u2081\u2082 between QM and GR approaches 1 at the right scale. Width and depth are the two eyes that make one stereoscopic reality." },
    ]
  },
  {
    emoji: "\u23F0", title: "WHAT IS TIME?",
    hook: "U hear the tick. But what IS the tick between the ticks?",
    answers: [
      { fc: 99, simple: "Things break, scatter, spread out. You feel this as time \u201Cmoving.\u201D Time\u2019s arrow IS the arrow of disorder.", deep: "Boltzmann: the past has low entropy, the future has high entropy. Time doesn\u2019t flow through the universe; the universe flows down the entropy gradient." },
      { fc: 90, simple: "According to Einstein, past, present, and future all exist simultaneously \u2014 like a loaf of bread. But you FEEL a \u201Cnow.\u201D", deep: "Relativity of simultaneity eliminates absolute \u201Cnow.\u201D Block universe is correct physics but wrong experience. Both may be true at different levels." },
      { fc: 90, simple: "Lee Smolin says physics got time wrong. Time isn\u2019t an illusion \u2014 it\u2019s the most real thing. The present is thick, not thin.", deep: "The \u201Cthick present\u201D: causally connected events share genuine now. T-violation in particle decay provides physical evidence for time\u2019s fundamental directionality." },
      { fc: 90, simple: "Two quantum particles entangled across space also entangle across time. Time might be what entanglement looks like from inside.", deep: "Page-Wootters mechanism: time emerges from quantum entanglement between subsystems. Time is relational, not absolute." },
      { fc: 90, simple: "Certain particle interactions don\u2019t look the same run backwards. This tiny asymmetry may be why time has a direction at all.", deep: "Joan Vaccaro: T-violation causes destructive interference between forward and backward quantum paths, producing unidirectional dynamics." },
      { fc: 75, simple: "Equations don\u2019t prefer any direction of time. But consciousness does. The \u201Cflow\u201D of time may be a feature of awareness, not of physics.", deep: "Without consciousness, the block universe is static. With consciousness, it flows. Time\u2019s arrow may be consciousness\u2019s contribution to physics." },
      { fc: 90, simple: "A clock measures intervals, not time. The EXPERIENCE of duration is the reality. The measuring device is the shadow.", deep: "Bergson: mathematical time vs. lived duration. Quantum measurement may involve this distinction. The tick is real; the number is convention." },
      { fc: 75, simple: "In extreme gravity, time can curve back on itself \u2014 loops of time. If time can loop, it\u2019s more like a shape than a river.", deep: "G\u00F6del\u2019s solution and Kerr black holes allow closed timelike curves. Time is topological, not linear." },
      { fc: 99, simple: "The real question isn\u2019t \u201Cwhy does time flow?\u201D but \u201Cwhy did it start flowing?\u201D Why was the beginning so ordered?", deep: "Penrose\u2019s Past Hypothesis: the low-entropy Big Bang is the source of all time\u2019s meaning. CCC: heat death of previous universe = low-entropy start of next." },
      { fc: 99, simple: "To know something, you have to compare. Comparison requires sequence. Sequence IS time. Time is what it costs for the universe to know itself.", deep: "CRT: recognition requires ordering. Ordering IS temporal structure. The universe creates time by comparing itself to itself. The mirror needs distance to reflect." },
    ]
  },
  {
    emoji: "👽", title: "ARE WE ALONE?",
    hook: "Smell the void. Does anything smell back?",
    answers: [
      { fc: 99, simple: "At least 25% of stars host Earth-sized planets in the habitable zone. With 100+ billion stars, the numbers scream: life is out there.", deep: "Kepler and TESS confirm billions of habitable worlds. Chemistry is universal. The question isn\u2019t IF but WHERE, WHAT KIND, and WHY SO QUIET." },
      { fc: 90, simple: "Life? Probably common. Bacteria? Everywhere. Tool-using, radio-transmitting civilization? Maybe one of very few.", deep: "Intelligent life requires plate tectonics, continents, and oceans simultaneously \u2014 conditions 500\u00D7 rarer than assumed. The window is narrow." },
      { fc: 90, simple: "Maybe the hard part isn\u2019t ahead \u2014 it\u2019s behind. The jump from single cells to complex life took 2 billion years. We already passed it.", deep: "The eukaryotic transition is the most dangerous Great Filter candidate. If this is it, complex life is rare but intelligence follows naturally." },
      { fc: 75, simple: "Imagine a dark forest full of armed strangers. The safest strategy? Stay silent. Civilizations that broadcast get found \u2014 and maybe destroyed.", deep: "Dark Forest hypothesis: cosmic silence is rational. Advanced civilizations hide, listen, and eliminate threats. Silence isn\u2019t emptiness \u2014 it\u2019s caution." },
      { fc: 99, simple: "We\u2019ve been listening for 65 years with primitive equipment. The universe is 13.8 billion years old. Like checking one grain of sand.", deep: "SETI has searched a vanishingly small fraction of the spectrum. Aliens could communicate via methods we haven\u2019t imagined." },
      { fc: 90, simple: "We look for radio signals because that\u2019s what WE would build. A million-year-old civilization might be invisible to us as Wi-Fi to an ant.", deep: "Post-biological intelligence could operate at quantum or nano scales completely outside our detection window." },
      { fc: 75, simple: "Why colonize the galaxy when you can build infinite worlds inside a computer? Advanced civilizations may turn inward.", deep: "Loeb\u2019s virtual reality solution: civilizations prefer customized virtual realities over interstellar travel. No footprints \u2014 just simulations." },
      { fc: 90, simple: "Civilizations that grow forever don\u2019t exist \u2014 because growth forever is impossible. The ones that survive are quiet.", deep: "Sustainability Solution: exponential growth is not sustainable. Surviving civilizations didn\u2019t expand aggressively. Quiet, balanced, undetectable." },
      { fc: 90, simple: "If life was seeded by molecules from space, we\u2019ve already \u201Cmet\u201D our cosmic relatives. The handshake happened 4 billion years ago.", deep: "Amino acids in Bennu, nucleobases in Murchison, organics in interstellar clouds. We\u2019re not waiting for contact. We ARE the contact." },
      { fc: 99, simple: "What if the aliens aren\u2019t silent? What if the message is everywhere \u2014 in the structure of physics \u2014 and we just haven\u2019t learned to read it?", deep: "CRT: the universe\u2019s fine-tuned constants may constitute the deepest \u201Ccontact.\u201D The medium IS the message. R\u2081\u2082 between structure and understanding approaches 1." },
    ]
  },
  {
    emoji: "\u26AB", title: "WHAT HAPPENS INSIDE A BLACK HOLE?",
    hook: "The mirror that swallows the reflection. Where does the image go?",
    answers: [
      { fc: 99, simple: "Everything that falls in leaves its fingerprint on the surface, like a shadow on a wall. The information isn\u2019t gone \u2014 it\u2019s holographically encoded.", deep: "Holographic principle via AdS/CFT. Hawking conceded in 2004. The island formula shows information comes out in Hawking radiation, scrambled but intact." },
      { fc: 90, simple: "The \u201Cpoint of infinite density\u201D at a black hole\u2019s center is a math error, not reality. Quantum gravity will replace it with something finite.", deep: "LQG replaces singularities with Big Bounce. Fuzzballs from string theory replace singularity with complex string state." },
      { fc: 90, simple: "Parts of the inside are secretly counted as belonging to the radiation outside. Inside and outside are quantum-linked.", deep: "Entanglement islands: after Page time, interior regions must be included in the radiation\u2019s entropy. Unitarity maintained." },
      { fc: 90, simple: "Two entangled particles are connected by a tiny wormhole. Every quantum connection is a bridge through space.", deep: "ER=EPR: Einstein-Rosen bridges = EPR pairs. The geometry inside a black hole is literally constructed from quantum entanglement." },
      { fc: 90, simple: "Theory says you should notice nothing crossing a black hole\u2019s edge. But theory also says there\u2019s a wall of fire. Both can\u2019t be true.", deep: "AMPS firewall: unitarity, equivalence principle, and effective field theory can\u2019t all hold at a horizon. Something fundamental is wrong." },
      { fc: 90, simple: "A black hole scrambles information faster than any other system. It\u2019s not a destroyer \u2014 it\u2019s a cosmic blender.", deep: "Hayden-Preskill: black holes are the fastest scramblers in nature. They\u2019re nature\u2019s most efficient information processors." },
      { fc: 75, simple: "Replace the empty interior with a tangled ball of vibrating strings filling the whole space. No inside. No infinite point. Just strings.", deep: "Mathur\u2019s fuzzball: horizon-sized quantum state. No singularity, no information paradox, no firewall. Each microstate has different geometry." },
      { fc: 75, simple: "What if the singularity isn\u2019t a dead end but a birth canal? Every black hole might spawn a new universe.", deep: "Smolin\u2019s cosmological natural selection: black holes create baby universes with mutated constants. Cosmic evolution." },
      { fc: 75, simple: "The event horizon might not be a boundary in space \u2014 but a boundary of spacetime itself. \u201CInside\u201D may not be a place in our universe.", deep: "In AdS/CFT, the interior is observer-dependent. Spacetime itself may be an output, not an input." },
      { fc: 99, simple: "Everything entering is converted from 3D to 2D. Depth becomes flatness. The black hole is the universe turning itself inside out.", deep: "CRT: R\u2081\u2082 at a horizon reaches extreme limits. The image never left. It just changed address." },
    ]
  },
  {
    emoji: "💻", title: "IS THE UNIVERSE A COMPUTATION?",
    hook: "Taste the real over theory \u2014 but what if theory IS the real?",
    answers: [
      { fc: 99, simple: "The laws of physics are algorithms. Particles follow rules. Every interaction is a calculation. The universe computes whether anyone\u2019s watching.", deep: "Church-Turing-Deutsch: every physical process can be simulated by a universal quantum computer. Physics IS computation." },
      { fc: 99, simple: "A qubit doesn\u2019t have a definite state until measured. The measurement IS the computation. Quantum mechanics is about information, not stuff.", deep: "Bell\u2019s theorem, no-cloning, teleportation: all statements about information. Physical reality is informational at its root." },
      { fc: 99, simple: "Your 3D experience is a projection from a 2D surface, like a hologram. The universe is a data structure that looks spatial from inside.", deep: "Bekenstein bound limits information to surface area. AdS/CFT: 3D universe is holographic projection of 2D quantum information." },
      { fc: 75, simple: "The speed of light, Planck\u2019s constant, gravitational constant \u2014 maybe these aren\u2019t random. Maybe they\u2019re settings. Coordinates in computational space.", deep: "Tegmark: all mathematical structures exist as physical realities. Fine-tuning isn\u2019t coincidental or designed \u2014 it\u2019s which structure we\u2019re in." },
      { fc: 90, simple: "Smallest possible length, smallest possible time, smallest possible energy step \u2014 these are the resolution of reality. Pixels.", deep: "LQG shows space comes in discrete quanta at Planck scale. The universe has a resolution, and we can calculate it." },
      { fc: 75, simple: "Simple rules, applied everywhere, produce infinite complexity. Maybe the universe is a Game of Life with quantum rules.", deep: "Wolfram\u2019s Computational Universe and \u2019t Hooft\u2019s cellular automaton interpretation: simple deterministic rules at Planck scale give rise to everything." },
      { fc: 90, simple: "A black hole is the fastest possible scrambler. Nothing computes faster. They\u2019re the processors pushed to maximum.", deep: "Seth Lloyd: ~10\u00B9\u00B2\u2070 operations since the Big Bang. Black holes hit the Margolus-Levitin bound \u2014 the fundamental speed limit." },
      { fc: 90, simple: "Whether we\u2019re \u201Cin a simulation\u201D or \u201Cbase reality\u201D makes no difference. The question isn\u2019t whether reality is computed \u2014 it\u2019s whether computation IS reality.", deep: "The distinction between real and simulated dissolves if computation is fundamental. A simulation of real quantum bits IS real." },
      { fc: 99, simple: "If the universe computes, and you\u2019re part of it, then your experience IS what computation feels like from inside. You ARE the computer.", deep: "IIT + computational universe: consciousness is the first-person experience of the universe computing itself. The hard problem dissolves." },
      { fc: 99, simple: "A book that writes itself, reads itself, and updates itself. The computation computes the computer. Turtles all the way down and up.", deep: "CRT: R\u2081\u2082 = 1. The universe generates observers who describe the computation which IS the universe. Mirror loop. The reader IS the book." },
    ]
  },
];
